/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AcademicStudent: typeof import('./src/components/profile/AcademicStudent.vue')['default']
    EditAcademicStudent: typeof import('./src/components/profile/EditAcademicStudent.vue')['default']
    EditInfoStudent: typeof import('./src/components/profile/EditInfoStudent.vue')['default']
    EditStudent: typeof import('./src/components/profile/EditStudent.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputPassword: typeof import('element-plus/es')['ElInputPassword']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    HeaderBar: typeof import('./src/components/layout/HeaderBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InfoStudent: typeof import('./src/components/profile/InfoStudent.vue')['default']
    MenuBar: typeof import('./src/components/layout/MenuBar.vue')['default']
    ProfileInfo: typeof import('./src/components/ssu/ProfileInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectCompany: typeof import('./src/components/ssu/SelectCompany.vue')['default']
    StudentView: typeof import('./src/components/profile/StudentView.vue')['default']
    StutentView: typeof import('./src/components/profile/StutentView.vue')['default']
  }
}
